pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=scala-steward
      - check-success=continuous-integration/circle-ci
    actions:
      merge:
        method: squash
        strict: smart
